project:
  type: website
  output-dir: docs

website:
  title: "R Tutorials for BST290"
  navbar:
    background: primary
  back-to-top-navigation: true
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
      - section: "Tutorials"
        contents:
        - href: tutorial_0.qmd
        - href: tutorial_1.qmd
        - href: tutorial_2.qmd
        - href: tutorial_3.qmd
        - href: tutorial_4.qmd
        - href: tutorial_5.qmd
        - href: tutorial_6.qmd
        - href: tutorial_7a.qmd
        - href: tutorial_7b.qmd
        - href: tutorial_8.qmd
        - href: tutorial_9.qmd
        - href: tutorial_10.qmd
        - href: tutorial_11.qmd
      - text: "---"
      - section: "Other"
        contents:
        - href: codereport.qmd


format:
  html:
    theme: flatly
    css: styles.css
    toc: true
execute:
  freeze: auto


